---
# tasks file for docker

- name: Add Yum Repository for Docker
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    enabled: yes
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes

- name: Install docker-engine
  yum:
    name: docker-engine
    enablerepo: dockerrepo
    state: latest

- name: Auto Start Docker Service
  service:
    name: docker
    state: started
    enabled: True

- name: Add Docker Control User
  user:
    name: "{{ docker_control_user }}"
    groups: docker
    append: yes
