---
# tasks file for runjob

- name: Get target HCL
  set_fact: 
    targetHCL: "{{ lookup('url', target_hcl, split_lines=False) | to_json }}"

- name: Convert HCL to JSON
  uri:
    url: "http://{{ manager_addr }}:4646/v1/jobs/parse"
    method: POST
    body: "{{ lookup('template', '../templates/hcl2json.json.j2') }}"
    body_format: json
  register: convert_result

- name: Set NomadJob JSON variable
  set_fact: 
    targetJSON: "{{ convert_result.json }}"

- name: Create Nomad Job
  uri:
    url: "http://{{ manager_addr }}:4646/v1/jobs"
    method: POST
    body: "{{ lookup('template', '../templates/createjob.json.j2') }}"
    body_format: json
