- name: Setup Application Servers
  hosts: application_server
  become: yes
  tasks:
    - debug:
        msg: "{{ groups['manager_server']| map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address'])| join('\",\"')  }}"
  roles:
    - role: docker
    - role: consul
      consul_server: False
    - role: nomad
      nomad_server: False
